import streamlit as st
import requests
from gtts import gTTS
import tempfile
import speech_recognition as sr
from fpdf import FPDF
import io
import time

# ---------------- CONFIG ---------------- #

SARVAM_API_KEY = st.secrets["SARVAM_API_KEY"]
SARVAM_URL = "https://api.sarvam.ai/v1/chat/completions"

st.set_page_config(page_title="AI Tamil Linguistic System", layout="wide")

st.title("AI அடிப்படையிலான தமிழ் எளிமைப்படுத்தல் மற்றும் இலக்கண பகுப்பாய்வு")

# ---------------- PDF GENERATION CLASS ---------------- #

class TamilPDF(FPDF):
    def header(self):
        # Add a header to each page
        self.set_font('freesans', '', 10)
        self.cell(0, 10, 'AI Tamil Linguistic System', 0, 1, 'C')
        self.ln(5)
    
    def footer(self):
        # Add a footer to each page
        self.set_y(-15)
        self.set_font('freesans', '', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')
    
    def add_tamil_text(self, text, title=""):
        # Add Tamil text with proper formatting
        self.add_page()
        
        # Add title if provided
        if title:
            self.set_font('freesans', 'B', 16)
            self.cell(0, 10, title, 0, 1, 'C')
            self.ln(5)
        
        # Add the main content
        self.set_font('freesans', '', 12)
        
        # Split text into lines and add to PDF
        lines = text.split('\n')
        for line in lines:
            # Check if line is a header (contains ### or **)
            if line.strip().startswith('###') or line.strip().startswith('**'):
                self.set_font('freesans', 'B', 12)
                self.multi_cell(0, 8, line.strip())
                self.set_font('freesans', '', 12)
            else:
                self.multi_cell(0, 8, line.strip())
            self.ln(2)

def create_pdf(content, mode, original_text):
    """Create PDF from the processed content"""
    
    pdf = TamilPDF()
    pdf.add_page()
    
    # Set font (using FreeSans which supports Tamil)
    pdf.set_font('freesans', '', 12)
    
    # Add metadata
    pdf.set_title("AI Tamil Linguistic System Output")
    pdf.set_author("Generated by AI Tamil Linguistic System")
    
    # Add header with timestamp
    pdf.set_font('freesans', 'B', 14)
    pdf.cell(0, 10, 'AI Tamil Linguistic System - Output Report', 0, 1, 'C')
    pdf.set_font('freesans', '', 10)
    pdf.cell(0, 10, f'Generated on: {time.strftime("%Y-%m-%d %H:%M:%S")}', 0, 1, 'R')
    pdf.ln(5)
    
    # Add mode information
    pdf.set_font('freesans', 'B', 12)
    pdf.cell(0, 10, f'Mode: {mode}', 0, 1)
    pdf.ln(5)
    
    # Add original text
    pdf.set_font('freesans', 'B', 12)
    pdf.cell(0, 10, 'Original Text:', 0, 1)
    pdf.set_font('freesans', '', 12)
    
    # Split original text into lines and add
    for line in original_text.split('\n'):
        pdf.multi_cell(0, 8, line.strip())
    pdf.ln(10)
    
    # Add separator line
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    # Add processed result
    pdf.set_font('freesans', 'B', 12)
    pdf.cell(0, 10, 'Processed Result:', 0, 1)
    pdf.ln(2)
    
    # Process the result with Tamil text handling
    pdf.add_tamil_text(content)
    
    return pdf.output(dest='S').encode('latin-1', errors='ignore')

# ---------------- MODE ---------------- #

mode = st.radio(
    "Mode தேர்வு செய்யவும்:",
    (
        "Phase 1: Any Language → Simple Tamil",
        "Phase 2: தமிழ் உரை → துல்லியமான இலக்கண பகுப்பாய்வு"
    )
)

st.markdown("---")

# ---------------- TEXT INPUT ---------------- #

text_input = st.text_area("உரை உள்ளிடவும்:", height=250)

# ---------------- VOICE INPUT (Phase 1 Only) ---------------- #

if mode.startswith("Phase 1"):
    audio_file = st.file_uploader("Voice Upload (wav)", type=["wav"])
    if audio_file:
        recognizer = sr.Recognizer()
        with sr.AudioFile(audio_file) as source:
            audio_data = recognizer.record(source)
            try:
                text_input = recognizer.recognize_google(audio_data, language="ta-IN")
                st.success("Voice converted to text")
            except:
                st.error("Voice recognition failed")

# ---------------- PROMPT GENERATOR ---------------- #

def generate_prompt(text, mode):

    # -------- PHASE 1 -------- #
    if mode.startswith("Phase 1"):
        return f"""
You are an experienced Tamil school teacher.

Task:
Simplify the given text into very easy, clear, modern Tamil.

Text:
{text}

STRICT INSTRUCTIONS:

1. Do NOT translate word-by-word.
2. First understand the full meaning.
3. Rewrite the content completely in simple spoken-style Tamil.
4. Break long sentences into 2 or 3 short sentences.
5. Replace difficult vocabulary with easy everyday Tamil words.
6. If the idea is complex, explain briefly in simple terms.
7. Maintain original meaning, but simplify structure.
8. Output must be natural and human-like.
9. Suitable for school students (age 12–16).
10. If input is already simple, improve clarity further.

Important:
- Do not copy original sentence structure.
- Do not use high literary Tamil.
- Do not add headings.
- Return only the simplified Tamil paragraph.
"""

    # -------- PHASE 2 -------- #
    else:
        return f"""
நீங்கள் ஒரு தமிழ் இலக்கிய மற்றும் இலக்கண நிபுணர்.

உரை:
{text}

-------------------------------------
### 1. இலக்கிய மற்றும் தத்துவ விளக்கம்

முக்கிய கட்டுப்பாடு:

- கீழே உள்ள ஒவ்வொரு பகுதியும் குறைந்தது 6 முதல் 7 முழு வாக்கியங்களைக் கொண்டிருக்க வேண்டும்.
- ஒரு வரி பதில் எழுதக்கூடாது.
- சுருக்கமாக எழுதக்கூடாது.
- தெளிவான பத்தி வடிவில் எழுத வேண்டும்.

A) நேரடி பொருள்:
(6–7 முழு வாக்கியங்களில் விரிவாக விளக்கவும்.)

B) உட்பொருள்:
(6–7 முழு வாக்கியங்களில் ஆழமான கருத்தை விளக்கவும்.)

C) வாழ்க்கை நெறி:
(6–7 முழு வாக்கியங்களில் நடைமுறை தொடர்பை விளக்கவும்.)

D) சமூக / மனவியல் கோணம்:
(6–7 முழு வாக்கியங்களில் சமூக மற்றும் மனவியல் விளக்கம் தரவும்.)

-------------------------------------
### 2. துல்லியமான இலக்கண பகுப்பாய்வு

1. முழு உரையில் இருந்து 100% உறுதியாக சரியான 3 அல்லது 4 சொற்களை மட்டும் தேர்வு செய்யவும்.
2. எந்த சந்தேகமும் உள்ள சொற்களை தேர்வு செய்யக்கூடாது.
3. வேற்றுமை அல்லது கால குழப்பம் உள்ள சொற்களை தவிர்க்கவும்.
4. மிகத் தெளிவான பெயர்ச்சொல் அல்லது வினைச்சொல் வடிவங்களை மட்டும் தேர்வு செய்யவும்.
5. சந்தேகம் இருந்தால் அந்த சொல்லை தவிர்க்கவும்.

வடிவம்:

சொல்:
அடிப்படை வடிவம்:
இலக்கண வகை:
விளக்கம்:

(அட்டவணை வேண்டாம். பட்டியலாக மட்டும் தரவும்.)

-------------------------------------
### 3. சுருக்கமான முடிவு

(4–5 முழு வாக்கியங்களில் கருத்தை தெளிவாக முடிக்கவும்.)
"""

# ---------------- SARVAM CALL ---------------- #

def call_sarvam(prompt, mode):

    headers = {
        "Authorization": f"Bearer {SARVAM_API_KEY}",
        "Content-Type": "application/json"
    }

    # Different temperature for each phase
    temperature = 0.3 if mode.startswith("Phase 1") else 0.2

    data = {
        "model": "sarvam-m",
        "messages": [
            {"role": "system", "content": "You are a Tamil linguistic expert."},
            {"role": "user", "content": prompt}
        ],
        "temperature": temperature,
        "max_tokens": 2000
    }

    response = requests.post(SARVAM_URL, headers=headers, json=data)

    if response.status_code != 200:
        return "Error occurred while contacting API."

    return response.json()["choices"][0]["message"]["content"]

# ---------------- PROCESS ---------------- #

if st.button("Process"):

    if text_input.strip() == "":
        st.warning("உரை உள்ளிடவும்")
    else:
        with st.spinner("Processing..."):
            prompt = generate_prompt(text_input, mode)
            result = call_sarvam(prompt, mode)

            st.markdown("---")
            st.markdown("### Processed Result")
            st.markdown(result)

            # Store result in session state for PDF generation
            st.session_state['last_result'] = result
            st.session_state['last_mode'] = mode
            st.session_state['last_text'] = text_input

            # Text-to-Speech only for Phase 1
            if mode.startswith("Phase 1"):
                tts = gTTS(result, lang="ta")
                temp_audio = tempfile.NamedTemporaryFile(delete=False, suffix='.mp3')
                tts.save(temp_audio.name)
                st.audio(temp_audio.name)
                
                # Add download button for audio
                with open(temp_audio.name, 'rb') as f:
                    audio_bytes = f.read()
                st.download_button(
                    label="🔊 Download Audio",
                    data=audio_bytes,
                    file_name=f"tamil_audio_{time.strftime('%Y%m%d_%H%M%S')}.mp3",
                    mime="audio/mp3"
                )

# ---------------- PDF DOWNLOAD SECTION ---------------- #

st.markdown("---")
st.markdown("### 📄 Download Options")

col1, col2 = st.columns(2)

with col1:
    if st.button("📥 Download as PDF"):
        if 'last_result' in st.session_state:
            with st.spinner("Generating PDF..."):
                try:
                    pdf_bytes = create_pdf(
                        st.session_state['last_result'],
                        st.session_state['last_mode'],
                        st.session_state['last_text']
                    )
                    
                    # Create filename based on mode
                    mode_prefix = "phase1" if st.session_state['last_mode'].startswith("Phase 1") else "phase2"
                    filename = f"tamil_linguistic_{mode_prefix}_{time.strftime('%Y%m%d_%H%M%S')}.pdf"
                    
                    st.download_button(
                        label="💾 Click to save PDF",
                        data=pdf_bytes,
                        file_name=filename,
                        mime="application/pdf",
                        key="pdf_download"
                    )
                    st.success("PDF generated successfully! Click the button above to download.")
                except Exception as e:
                    st.error(f"Error generating PDF: {str(e)}")
        else:
            st.warning("Please process some text first before downloading PDF.")

with col2:
    if st.button("📋 Copy to Clipboard"):
        if 'last_result' in st.session_state:
            # Use Streamlit's built-in clipboard functionality
            st.code(st.session_state['last_result'], language='text')
            st.info("Select all text above and copy (Ctrl+C / Cmd+C)")
        else:
            st.warning("No result to copy. Please process some text first.")

# Add information about PDF download
with st.expander("ℹ️ About PDF Download"):
    st.markdown("""
    **PDF Download Features:**
    - Download processed results as PDF
    - Includes original text and processed output
    - Tamil text support
    - Timestamp and mode information included
    - Suitable for both Phase 1 and Phase 2 outputs
    
    **Note:** Make sure to process text first before downloading PDF.
    """)
